from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import xml.etree.ElementTree as ET

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


@dataclass
class SuiteSummary:
    name: str
    tests: int
    failures: int
    errors: int
    skipped: int
    time_seconds: str

    @property
    def passed(self) -> int:
        return self.tests - self.failures - self.errors - self.skipped


def parse_junit(path: Path, default_name: str) -> SuiteSummary:
    root = ET.parse(path).getroot()

    if root.tag == "testsuite":
        suite = root
    elif root.tag == "testsuites":
        suite = root.find("testsuite")
        if suite is None:
            return SuiteSummary(default_name, 0, 0, 0, 0, "0")
    else:
        return SuiteSummary(default_name, 0, 0, 0, 0, "0")

    return SuiteSummary(
        name=suite.attrib.get("name", default_name),
        tests=int(suite.attrib.get("tests", "0")),
        failures=int(suite.attrib.get("failures", "0")),
        errors=int(suite.attrib.get("errors", "0")),
        skipped=int(suite.attrib.get("skipped", "0")),
        time_seconds=suite.attrib.get("time", "0"),
    )


def write_pdf(path: Path, title: str, summaries: list[SuiteSummary]) -> None:
    c = canvas.Canvas(str(path), pagesize=A4)
    width, height = A4
    y = height - 60

    c.setTitle(title)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(40, y, title)
    y -= 30

    c.setFont("Helvetica", 11)
    c.drawString(40, y, "Generated by GitHub Actions")
    y -= 30

    for summary in summaries:
        c.setFont("Helvetica-Bold", 12)
        c.drawString(40, y, f"Suite: {summary.name}")
        y -= 18

        c.setFont("Helvetica", 11)
        rows = [
            f"Tests: {summary.tests}",
            f"Passed: {summary.passed}",
            f"Failures: {summary.failures}",
            f"Errors: {summary.errors}",
            f"Skipped: {summary.skipped}",
            f"Duration (s): {summary.time_seconds}",
        ]
        for row in rows:
            c.drawString(55, y, row)
            y -= 16

        y -= 12
        if y < 120:
            c.showPage()
            y = height - 60

    c.save()


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate PDF test summaries from JUnit XML reports.")
    parser.add_argument("--ui-junit", required=True, type=Path)
    parser.add_argument("--api-junit", required=True, type=Path)
    parser.add_argument("--out-dir", required=True, type=Path)
    args = parser.parse_args()

    args.out_dir.mkdir(parents=True, exist_ok=True)

    ui_summary = parse_junit(args.ui_junit, "ui")
    api_summary = parse_junit(args.api_junit, "api")

    write_pdf(args.out_dir / "ui-summary.pdf", "UI Test Report", [ui_summary])
    write_pdf(args.out_dir / "api-summary.pdf", "API Test Report", [api_summary])
    write_pdf(args.out_dir / "combined-summary.pdf", "Combined Test Report", [ui_summary, api_summary])


if __name__ == "__main__":
    main()
